### ISSUE TITLE
Component: Select

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-web-components#229]

**Comment by RobertaJHahn** [comment]
@asudoh Why is this issue in Review?   It doesn't contain a description and is not assigned to this sprint.

**Comment by asudoh** [comment]
@RobertaJHahn Oh probably I misunderstood the purpose of the pipeline; I put it simply because there is PR in review.

**Comment by RobertaJHahn** [comment]
@asudoh You are correct about the purpose of the pipeline, but as you have observed in the meetings we use labels and assignments to track the work and do reporting.  If you are working on this issue, then you should assign it to yourself.  If you are working on it in the current sprint, then the sprint should be assigned.  We also use labels to categorize the work between design and dev, web components and react.  Is this a React or Web Components component?  Could you add this label?  `package: react` or `package: web components`

I also add the issue to an Airtable where the velocity is tracked.  

Let me know if you have any questions.

**Comment by asudoh** [comment]
Thanks for the info @RobertaJHahn! Added the label. This is an old issue that was created before `carbon-web-components` repo is integrated into our project scheme.

**Comment by RobertaJHahn** [comment]
@asudoh I noticed that after I posted the comment about the component label.  When moving an issue from one repo to another you loose all of the information associated with the issue.  (milestone, labels, release....)  I have gotten burned by that situation in the past.  Thanks for the update.

**Comment by asudoh** [comment]
Work finished, the feature available at: https://carbon-web-components.netlify.app
