### ISSUE TITLE
Notification proposal

### ISSUE THREAD

**Issue by Tansito** [carbon-design-system/carbon-web-components#291]
Something that we are trying to achieve with the notification component is to close the notification after X ms but by now and from what I could investigate through the code and storybook the library doesn't have yet a `open` and a `close` event to modify the notification behaviour. 

Looking into the [spec](https://www.carbondesignsystem.com/components/notification/code) for this component it seems that it has a `remove` event to handle this kind of things. I don't know if it can be possible to implement it.

**Comment by asudoh** [comment]
Hi 👋 it's proposed in core Carbon repo (Issue# 4666) sometime before, and nobody seems to have opposed to it. From application code, it can be done by changing `open` attribute after timeout. (It can be seen at Storybook Knobs panel e.g. at http://localhost:9000/?path=/story/notifications--inline)

**Comment by Tansito** [comment]
If there is no problem I would like to start to work in this feature @asudoh

**Comment by asudoh** [comment]
It sounds great, looking forward to seeing a PR @Tansito!
