### ISSUE TITLE
Bug: Number Input

### ISSUE THREAD

**Issue by frodesigns** [carbon-design-system/carbon-web-components#410]
Clicking the number spinner arrows does not trigger an @input event. The @input event needs to be triggered to fetch the updated value.

**Comment by asudoh** [comment]
Thank you for catching this @frodesigns - Looks that we need to do something similar to [checkbox](https://github.com/carbon-design-system/carbon-custom-elements/blob/v1.0.0-rc.3/src/components/checkbox/checkbox.ts#L33-L47). CC @cal-smith 

Meanwhile, you can attach `click` event listener to `<bx-number-input>` and call [`event.composedPath()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) to see if the event came from the spinner button.

**Comment by frodesigns** [comment]
Thank you for this suggestion. I gave it a try, but the arrow clicks don't seem to actually change the value either, so I ended up having to increment/decrement manually.

**Comment by asudoh** [comment]
> the arrow clicks don't seem to actually change the value

I couldn't reproduce it, at [our storybook env](https://custom-elements.carbondesignsystem.com/iframe.html?id=components-number-input--default-story) - Wondering if your event handler calls `.preventDefault()`.

Anyhow, great that you found a solution! 🎉

**Comment by asudoh** [comment]
Closing as inactive. @frodesigns Please don't hesitate to speak up if you can still reproduce this issue. Thanks!
