### ISSUE TITLE
Data table: Tabbing away from batch action bar hides the bar

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-web-components#467]
## Detailed description

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

A bug.

> Is this issue related to a specific component?

Yes, data table.

> What browser are you working in?

Chrome `84.0.4147.105`

> What version of Carbon Web Components are you using?

`v1.4.0`

## Steps to reproduce the issue

1. https://web-components.carbondesignsystem.com/iframe.html?id=components-data-table--sortable&knob-Supports%20selection%20feature%20(has-selection)=true
2. Select a row
3. Click on a blank area above the table
4. Keep hitting tab key until the focus goes into the batch action bar
5. Keep hitting tab key until the focus goes out of the batch action bar

BUG: The batch action bar is hidden. Expected to see the batch action bar kept.

**Comment by RobertaJHahn** [comment]
Added to Aug 31 Engineering meeting agenda.

**Comment by RobertaJHahn** [comment]
@asudoh Just cleaning up the issues related to the Carbon Web Components January 13 release. This issue is included in the release, but doesn't appear to be finished. Should I move this issue to the next release in March?

cc: @jeffchew

**Comment by RobertaJHahn** [comment]
@asudoh I just found my notes about the scheduling of this issue.  Moving to the March release.  

cc:  @jeffchew
