### ISSUE TITLE
Dropdown: Fire a custom event on toggling

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-web-components#475]
### The problem

When we want to control the open state to dropdown, the component that controls the dropdown needs to know the change in open state.

### The solution

Fire a custom event in `<bx-dropdown>`, when such state changes.

**Comment by RobertaJHahn** [comment]
@asudoh This issue was reviewed in our refinement meeting earlier today.  In order to determine the priority, Jeff would like to know whether this work is related to any work for ibm.com Library or whether it is to maintain parity with Carbon React.  Thanks.

**Comment by asudoh** [comment]
Hi @RobertaJHahn it's neither of them - It's a use case I found using `<bx-dropdown>` in my personal project.

**Comment by RobertaJHahn** [comment]
@asudoh Just cleaning up the issues related to the Carbon Web Components January 13 release. This issue is included in the release, but doesn't appear to be finished. Should I move this issue to the next release in March?

cc: @jeffchew

**Comment by RobertaJHahn** [comment]
@asudoh I just found my notes on the scheduling of this issue.  Moving to the March release.  

cc:  @jeffchew
