### ISSUE TITLE
Typeahead search

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-web-components#479]
### The problem

Carbon Angular team is introducing typeahead search IBM/carbon-components-angular#1486 which is good to have.

### The solution

Implement it.

**Comment by RobertaJHahn** [comment]
Management decisions of the Carbon web components is needed before this issue can be moved forward.  Roberta will add to the Leadership meeting agenda.

**Comment by RobertaJHahn** [comment]
This is still being developed by the Carbon Angular team.  Will wait until this work is finished.

**Comment by RobertaJHahn** [comment]
Not part of Core.  Closing
