### ISSUE TITLE
Data Table: Support for colspan and rowspan

### ISSUE THREAD

**Issue by frodesigns** [carbon-design-system/carbon-web-components#481]
### The problem

Data Table cells currently cannot span more than one row or column, but many use-cases require this.

### The solution

Implement colspan and rowspan support to match native HTML tables.

**Comment by asudoh** [comment]
Nice to have brought this up @frodesigns - Seems that we are hitting a limitation in web platform. Apple is against "type extension" (aka `<td is="bx-table-cell">`) which means we cannot create a custom element that behaves as a native `<td>`. We are using `display: table-cell` trick to work around it but it doesn't work with `colspan`/`rowspan` (I wish there was a CSS counterpart those attribute). So, I think the most viable solution here for now is using vanilla table markup (without using vanilla JavaScript).

**Comment by asudoh** [comment]
Closing as viable workaround available, but please let us know if there are any more questions, etc. Thanks!
