### ISSUE TITLE
Create release manager playlist for carbon-web-components

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-web-components#493]
#### User Story

> As a `[user role below]`:
Carbon Web Components release manager

> I need to:
have a playlist on what to do when running a release

> so that I can:
make sure I do not miss any steps when releasing to npm

#### Additional information

 - We have an existing playlists for both full releases and patch releases for the IBM.com Library, can can be used as a template: 
  - Release playlist: https://ibm.ent.box.com/notes/497596874716
  - Patch release playlist: https://ibm.ent.box.com/notes/525233931289
- Going to open another issue for looking into `semantic-release`, which can dictate what this playlist can look like
- Should think about if we want to follow the same code freeze tasks and timeline approach (release candidates, etc)

#### Acceptance criteria
 - [ ] Playlist created and added to team Box folder
 - [ ] Include the corresponding announcements to slack, etc

**Comment by asudoh** [comment]
Posted at: https://ibm.biz/BdqQwx
