### ISSUE TITLE
Compatibility issues with Safari 14

### ISSUE THREAD

**Issue by ericwwsun** [carbon-design-system/carbon-web-components#494]
## Detailed description

We are noticing when clicking on some components will crash the browser, Safari version 14 in particular. We are not sure if that is caused by the component or the browser, but the problem can be reperduce in the storybook. 

## Steps to reproduce the issue

1. Go to https://web-components.carbondesignsystem.com/?path=/story/components-content-switcher--default-story with Safari version 14
2. The default selected switcher isn't highlighted
3. Click on any options, the browser crashes and reloads the page.

## Additional information

<img width="1184" alt="Screen Shot 2020-09-23 at 5 40 47 PM" src="https://user-images.githubusercontent.com/1548212/94072584-f50de500-fdc3-11ea-96cd-4ed39a45ef54.png">

The same problem can be found in checkbox component 
https://web-components.carbondesignsystem.com/?path=/story/components-checkbox--default-story

**Comment by asudoh** [comment]
Thanks @ericwwsun for reporting! Fixed browser crash. Wrt selection, no selection at the initial state is consistent with Chrome and is intentional. You can go to Knobs tab and set something like `staging` to `The value of the selected item (value)` knob to see the selection.
