### ISSUE TITLE
Tabs: Add light variant

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-web-components#498]
### The problem

Carbon core recently implemented `light` variant of tabs.

### The solution

Implement it.

**Comment by RobertaJHahn** [comment]
@asudoh Just cleaning up the issues related to the Carbon Web Components January 13 release.  This issue is included in the release, but doesn't appear to be finished.  Should I move this issue to the next release in March?

cc:  @jeffchew

**Comment by RobertaJHahn** [comment]
@asudoh I just found my notes on the scheduling of this issue.  Moving it to the March release.  

cc:  @jeffchew
