### ISSUE TITLE
Web component: Text input - Prod QA testing of the fluid variant

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-web-components#510]
#### User Story

> As a `[user role below]`:
developer using the carbon web components Library `Text input` fluid variant

> I need to:
have a version of the component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic for the Design and Functional specs information**
 - Dev issue (#491) 
- [Carbon Web Components Production Instance]( https://web-components.carbondesignsystem.com)
- Once development is finished the updated code is available in the [** Carbon Web Components test environment**](https://carbon-web-components.netlify.app)

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Component is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by RobertaJHahn** [comment]
@asudoh I have created the dev issues for the Fluid Form work.  They are all linked to epic (#477).  I would like to create the corresponding Prod QA testing issues.  When creating multiple issues for the same type of work, I usually do this by creating the first issue and us it as a template for the others.  Is there are Carbon Web Components environment that Praveen would use for testing?  Do we need the React Canary link in this Prod QA testing issue?  Are there another other references that I should include?

cc:  @jeffchew

**Comment by asudoh** [comment]
@RobertaJHahn Yes it's: https://carbon-web-components.netlify.app

**Comment by RobertaJHahn** [comment]
Closing this issue as the Prod QA testing will be automated.
