### ISSUE TITLE
Incorrect rendering of <bx-header> and <bx-side-nav> combination. Missing global styles?

### ISSUE THREAD

**Issue by pschyska** [carbon-design-system/carbon-web-components#548]
## Detailed description

I'm experimenting with the UI shell components at the moment and I noticed some differences in rendering to the "official" components (e.g. react, Vanilla variants). I'm not sure if I'm doing something wrong.

My HTML is minimal:

````html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>m14r</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      m14r-main {
        transition: opacity 200ms ease-out;
      }
      /* prevent FOUC */
      m14r-main:not(:defined) {
        opacity: 0;
      }
    </style>
  </head>
  <body>
    <m14r-main></m14r-main>
    <script type="module" src="./index.js"></script>
  </body>
</html>
````

My Component looks like this:

````ts
import {
  css,
  customElement,
  html,
  LitElement,
  TemplateResult,
} from "lit-element";
import "carbon-web-components/es/components/ui-shell/header";
import "carbon-web-components/es/components/ui-shell/header-name";
import "carbon-web-components/es/components/ui-shell/header-menu-button";
import "carbon-web-components/es/components/ui-shell/side-nav";
import "carbon-web-components/es/components/ui-shell/side-nav-link";

@customElement("m14r-main")
export class Main extends LitElement {
  static styles = css`
    * {
      box-sizing: border-box;
    }

    bx-header ~ bx-side-nav {
      margin-top: 3rem;
      height: calc(100% - 3rem);
    }

    bx-header ~ .bx--content {
      margin-left: 16rem;
      margin-top: 3rem;
      height: calc(100% - 3rem);
      width: calc(100% - 16rem);
    }
  `;

  render(): TemplateResult {
    return html`
      <bx-header>
        <bx-header-menu-button></bx-header-menu-button>
        <bx-header-name prefix="">M14R</bx-header-name>
      </bx-header>
      <bx-side-nav>
        <bx-side-nav-link href="javascript:void(0)" active
          >Item</bx-side-nav-link
        >
        <bx-side-nav-link href="javascript:void(0)"
          >Another Item</bx-side-nav-link
        >
      </bx-side-nav>
      <main class="bx--content">
        <h1>UI Shell Content</h1>

        <p>
          <strong>Pellentesque habitant morbi tristique</strong> senectus et
          netus et malesuada fames ac turpis egestas. Vestibulum tortor quam,
          feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero
          sit amet quam egestas semper.
          <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo.
          Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat
          wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet,
          wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum
          rutrum orci, sagittis tempus lacus enim ac dui.
          <a href="#">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.
        </p>
      </main>
    `;
  }
}
````

Without the added styles, I get incorrect rendering like this:

![Screenshot from 2020-12-01 20-49-25](https://user-images.githubusercontent.com/356257/100789524-db69c900-3416-11eb-8b9b-42d889ad7944.png)

Specifically:
1. The spacing rule for header (and many similar) seems to be globally defined in the Carbon stylesheets. However, they were missing from my environment. Am I supposed to wrap the custom element invocations in a specific way to get them? Including the carbon css globally didn't work because these styles don't affect m14r-main's shadow dom. Also I understood it would be incorrect to do so anyways, as the web components already carry the relevant rules in their constructed style sheets. What did work, but leads to styles being loaded twice, is to return a `<link rel=stylesheet>` from render(). Defining this myself feels wrong:
````css
    bx-header ~ bx-side-nav {
      margin-top: 3rem;
      height: calc(100% - 3rem);
    }
````
2. `box-sizing: border-box;` seems to come from [css-reset](https://raw.githubusercontent.com/carbon-design-system/carbon/master/packages/components/src/globals/scss/_css--reset.scss) in the storybook. Missing this rule even with the `bx-header ~ bx-side-nav ` above, I would get a 1px error where the side-nav would overlap the header (as the header has a bottom border of 1px). As css-reset has many other rules I'm not sure if I'm missing some additional ones that just didn't appear yet in my testing.

Is there a way to somehow grab just the "global" style bits into my components? Including the sibling styles (for spacing, etc.), reset styles and other stuff that doesn't really belong to a specific element like <bx-header>, and I might be missing. Then I could include them in each of my elements like `<m14r-main>` above (assuming they don't weigh a ton because they will be duplicated in all of my components).

3. I wondered if defining `<main class=bx--content>` myself is correct. I noticed this is a Carbon concept, and there are rules and mixins (carbon-content ?) defined, but couldn't find an equivalent wrapper in carbon-web-components. I looked for something like `<bx-content>` which would encapsulate the layout and typography, etc.

**Comment by asudoh** [comment]
Hi @pschyska thank you for those questions!

1. Created #549 to clearly document that the style needs to be added in the application code.
2. It can be done by importing [`_css--reset.scss`](https://github.com/carbon-design-system/carbon/blob/v10.23.0/packages/components/src/globals/scss/_css--reset.scss) into your Sass code, or by generating CSS from that Sass file.
3. The `<main>` should be replaced with your application content. `<main class="bx--content">` is there solely for demonstration purpose.

Hope above helps - Let us know if you have any follow-up questions.

**Comment by pschyska** [comment]
1. I think `bx-header ~ bx-side-nav` is not enough in general. There are more things to consider: Any type of UI shell content must be pushed down (let's say a rule `bx-header ~ bx--content`), and when the side nav is supposed to be fixed, which it is IIUC by default when using the header+responsive-mode side-nav (and screen is above the breakpoint), the content should have a left margin of some sort. I think it's unfortunate to not being able to use the default Carbon rules (I'm completely new to the design system as well, so I don't know if this issue would pop up often, or if it's isolated with the ui shell components).
I realize it's not trivial, because the [upstream rules](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/ui-shell/_side-nav.scss#L142) - i.e. `.#{$prefix}--header ~ .#{$prefix}--side-nav` - wouldn't work due to isolation and the fact that in the web components case `bx--header` and `bx--side-nav` aren't direct siblings in the first place (for that reason it's also probably impossible to have the derived components adopt a shared style sheet containing all the cross-cutting rules like that).
2. I had hoped I could get around pulling a sass processor into my build. So far I could get away with a simple esbuild-based solution :-) I think it would be great if carbon-web-components could provide a [CSSResult](https://lit-element.polymer-project.org/api/classes/_lit_element_.cssresult.html) somewhere as importable ES module. Then users could:

````ts
import {reset} from "carbon-web-components/es/something/something/css-reset";

@customElement("m14r-main")
export class Main extends LitElement {
  static styles = [reset, css`
    :host {
      something...
    }
  `]
}
````

There is a way to make this efficient in the browser, so that all the components using `reset` adopt the same constructed style sheet and don't incur the costs each time it's included in a component (which could be dozens of time if you build small components). I don't know if the simplistic solution above (importing CSSResult and refering) would do that though.

3. I understand that the `<main class=bx--content>` is just a placeholder here. I was talking about the ruleset associated to `bx-content`. I would have to pull it into each of my components because there is no component in carbon-web-components that bundles that. So `bx--content` is defined for UI shell [here](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/ui-shell/_content.scss), but I have to know and look it up and define it myself. I'd rather have a way to write something like `<bx-content><mainorwhatever>..` and get these rules automatically.

Anyhow, I was wondering if I'm doing anything wrong in principle and it appears I'm not, so I'm gonna close this issue.
