### ISSUE TITLE
[Tooltip] Alignment option in interactive tooltip

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-web-components#551]
### The problem

Carbon core is adding alignment option in interactive tooltip.

https://github.com/carbon-design-system/carbon/pull/7309

### The solution

Implement it.

**Comment by oliviaflory** [comment]
Assuming this is the alignment of where the caret is on the tooltip, would be great to get this in, I think I've seen our team suggesting the alignment on our own components that would utilize tooltip.

https://react.carbondesignsystem.com/?path=/story/components-tooltip--default-bottom

<img width="1443" alt="Screen Shot 2022-01-10 at 11 37 02 AM" src="https://user-images.githubusercontent.com/45692622/148803123-c278ed33-ff01-4678-bd9b-c5b6c2f0b3ac.png">

**Comment by emyarod** [comment]
we may also need to update with some follow up features:

https://github.com/carbon-design-system/carbon/pull/9556
https://github.com/carbon-design-system/carbon/pull/9606
