### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by Kikobeats** [carbon-design-system/carbon-web-components#566]
<img width="1524" alt="Screen Shot 2021-01-05 at 10 56 49" src="https://user-images.githubusercontent.com/2096101/103632547-c10a9a00-4f44-11eb-8142-4d878ecd877b.png">

**Comment by abdonrd** [comment]
It seems that carbondesignsystem.com domain is not working.

Ping to @asudoh.

**Comment by asudoh** [comment]
Thanks @Kikobeats for reporting and @abdonrd for the follow-up. Just to share the interim update, the website is back up and running with a new host (GH pages).

**Comment by Kikobeats** [comment]
thanks for that!
