### ISSUE TITLE
[Modal]: Modals with open=false flash in Firefox

### ISSUE THREAD

**Issue by frodesigns** [carbon-design-system/carbon-web-components#588]
## Detailed description

We've noticed recently in Firefox that modals with `?open="${false}` are flashing on the screen briefly on page load (starts visible, fades out).  We haven't updated our Carbon dependencies, so maybe it is related to a recent change in Firefox itself?

**Comment by asudoh** [comment]
@frodesigns Thank you for reporting - Tried to apply `?open="${false}"` at the [modal story](https://github.com/carbon-design-system/carbon-web-components/blob/v1.11.0/src/components/modal/modal-story.ts#L41), but couldn't reproduce this, even after I upgraded Firefox. Do you want to fork [our CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon-web-components/tree/master/examples/codesandbox/basic) and put your code there to see if it reproduces in an environment that we can re-create?

**Comment by frodesigns** [comment]
I narrowed it down to something a developer added to our own codebase. They had added a `firstUpdated()` function to our modal wrapper component, which I think was adding an extra render cycle before the open=false was being set in the `constructor()` causing it to flash as "open" briefly.  Thanks, and sorry for wasting your time!

**Comment by asudoh** [comment]
No problem and thanks @frodesigns for the analysis!
