### ISSUE TITLE
Create Carbon Web Components with Expressive Theme

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-web-components#605]
#### User Story

> As a `[user role below]`:
Carbon Web Components developer

> I need to:
create an experience with the expressive theme using Carbon Web Components

> so that I can:
develop my application with expressive moments

#### Additional information

- Currently there is the agnostic styles/theme for expressive, applied to React as an example: https://carbon-expressive.mybluemix.net

#### Acceptance criteria

- [ ] Ability to utilize Carbon Web Components with the expressive theme applied
- [ ] Examples in storybook and corresponding documentation on how to implement within an application

**Comment by asudoh** [comment]
@jeffchew Would we be able to separate out expressive theme code to `@carbon/expressive` so `carbon-web-components` can consume? Thoughts? Thanks!

**Comment by RobertaJHahn** [comment]
No longer needed.  Closing
