### ISSUE TITLE
Register the namespace "bx"

### ISSUE THREAD

**Issue by nuxodin** [carbon-design-system/carbon-web-components#606]
Maybe you want to register the namespace "bx" here with a pull request?
https://github.com/nuxodin/web-namespace-registry

**Comment by asudoh** [comment]
@jeffchew Thoughts? Thanks!

**Comment by asudoh** [comment]
CC @abdonrd @Tansito

**Comment by abdonrd** [comment]
Probably scoped registries be a better solution. But yeah, I'm ok with it!

**Comment by asudoh** [comment]
Yeah good point @abdonrd, probably an interim thing.
