### ISSUE TITLE
Styling the Header

### ISSUE THREAD

**Issue by JacobWeinbren** [carbon-design-system/carbon-web-components#626]
## Summary
How do I style the UI Shell Header for use with Wordpress? Which is the best method to approach this problem?

## Relevant information
It seems like the UI Shell relies on Shadow DOM. This complicates matters somewhat. You can't access the Header through themes or the carbon variables, as the UI Shell relies on the IBM Language Design Palette. There are essentially three approaches I can see to this. 

1. You can use the `::part` selector
This works, though it is problematic as polyfill has mixed support here, also I think this goes against the intent of separating elements from the main CSS. This would make the site unusable on IE and various mobile browsers too.

2. You can use lit-element
This is difficult, as I am using this within a WordPress theme. Lit-Element typially works with html-loader by injecting the necessary content into the HTML as a build step. There are some workarounds to make it work for multiple HTML (or in this case PHP) pages. Technically this is possible, but I do not fully understand how to separate the entry points for JS/CSS or how this adapts to the WordPress model of the page (which has separate pages for the header, footer etc.). I do not think I am experienced enough to go down this route. 

Without html-loader, it breaks. This might be a separate issue of it's own, but extending `BXHeader` is not working for me.

```
class TSRHeader extends BXHeader {}

TSRHeader.styles = [
  BXHeader.styles,
  css`
    bx-header {
      background-color: white;
    }
  `,
];

customElements.define('tsr-header', TSRHeader);
```

You can see my attempt of the issue here https://github.com/JacobWeinbren/miliband - a preview of the result is attached
<img width="287" alt="Screenshot 2021-04-19 at 06 37 57" src="https://user-images.githubusercontent.com/5209161/115186559-d9f52080-a0d9-11eb-8310-7c20e48cc3b1.png">

3. Rebuild the Header, and use the copied version to change the link text colour
I think this would take a while, has this been done outside of the [the carbon components](http://the-carbon-components.netlify.app)?

Any advice would be really appreciated.

Thanks
Jacob

**Comment by asudoh** [comment]
Hi @JacobWeinbren I don't know much about WordPress, but the guidance of custom styling, including some of what you tried, can be found at https://github.com/carbon-design-system/carbon-web-components/blob/v1.13.0/docs/styling.md. A fully customized version UI shell header can be found at https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-masthead--default, whose source code is at https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/v1.17.0/packages/web-components/src/components/masthead/.

BTW in your code:

```typescript
class TSRHeader extends BXHeader {}

TSRHeader.styles = [
  BXHeader.styles,
  css`
    bx-header {
      background-color: white;
    }
  `,
];
```

I wonder if you meant setting `tsr-header` tag selector (instead of `bx-header` tag selector in your above code), because you are using your `<tsr-header>` instead of `<bx-header>`.

**Comment by JacobWeinbren** [comment]
Thanks for getting back and letting me know - I will need to learn how to use react but hopefully, this is possible. For record, I did manage to get this working, and it was through a revision of the code to the following.

```
TSRHeader.styles = [
  TSRHeader.styles,
  css`
    :host(tsr-header) {
      background-color: white;
    }
  `,
];
```

**Comment by asudoh** [comment]
Great that you made it work @JacobWeinbren! For React usage, please refer to: https://github.com/carbon-design-system/carbon-web-components#react
