### ISSUE TITLE
Loading component not animating?

### ISSUE THREAD

**Issue by aca02djr** [carbon-design-system/carbon-web-components#645]
I'm trying to get a simple demo of the loading component running but the animations on it are not working, am I setting anything up wrong here?

I forked the example code sandbox and modified it to demostrate:

[https://codesandbox.io/s/lingering-morning-te2xk?file=/index.html](https://codesandbox.io/s/lingering-morning-te2xk?file=/index.html)

Thanks :)

**Comment by asudoh** [comment]
@aca02djr Would you want to try adding `display: block` to `<bx-loading>`?

**Comment by aca02djr** [comment]
Ah yes that sorted it. Thank you!

**Comment by asudoh** [comment]
🎉 @jeffchew Would the team want to add that style in the component so we can ensure it works OOTB? Thanks!
