### ISSUE TITLE
Carbon Slider out of range when min != 0

### ISSUE THREAD

**Issue by tambien** [carbon-design-system/carbon-web-components#647]
## Detailed description

When the slider's min value is not 0, it goes out of the edges of the slider range. 

Here's a demo https://codesandbox.io/s/carbon-slider-issue-c7dsv

## Steps to reproduce the issue

1. Create a `<bx-slider>`
2. Set `min` to anything that's not 0
3. Adjust the slider range to the max value

## Additional information

![image](https://user-images.githubusercontent.com/1323402/120714795-b15e9580-c491-11eb-8209-cb5cbe311e1a.png)

Tested on latest Chrome

**Comment by asudoh** [comment]
Wondering if the team wants to subtract `min` from `value` before dividing it by the range, at [`.rate` getter](https://github.com/carbon-design-system/carbon-web-components/blob/v1.13.3/src/components/slider/slider.ts#L86-L90). The repo welcomes contributions, too @tambien!
