### ISSUE TITLE
[Data Table with Search] Search functionality is broken

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-web-components#656]
## Detailed description

> Describe in detail the issue you're having.

After upgrading to Carbon v10.37.0, it looks like the search icon gets shifted to the left:

![image](https://user-images.githubusercontent.com/1641214/121751106-8dc3cc80-cadb-11eb-83f2-3b2cc317d767.png)

However, regardless of that, the search doesn't appear to be working even before the Carbon upgrade:

![Kapture 2021-06-11 at 17 38 14](https://user-images.githubusercontent.com/1641214/121751374-fc088f00-cadb-11eb-8592-141036d78b16.gif)

Prod link:
https://web-components.carbondesignsystem.com/?path=/story/components-data-table--sortable-with-pagination

**Comment by asudoh** [comment]
Weighing in; Wondering if @jeffchew and the team want to manually bring back the following, that seems to have lost with recent Carbon core updates:

* [`position: relative` CSS rule](https://github.com/carbon-design-system/carbon/blob/v10.36.0/packages/components/src/components/data-table/_data-table-action.scss#L62) used from [our `:host(#{$prefix}-table-toolbar-search)` selector](https://github.com/carbon-design-system/carbon-web-components/blob/v1.13.0/src/components/data-table/_table-action.scss#L54)
* [`flex: auto` and `transision: flex 175ms $carbon--standard-easing` CSS rules](https://github.com/carbon-design-system/carbon/blob/v10.36.0/packages/components/src/components/data-table/_data-table-action.scss#L495) used from [our `:host(#{$prefix}-table-toolbar-search[expanded])` selector](https://github.com/carbon-design-system/carbon-web-components/blob/v1.13.0/src/components/data-table/_table-action.scss#L86)
* [`width: 100%` CSS rule](https://github.com/carbon-design-system/carbon/blob/v10.31.0/packages/components/src/components/data-table/_data-table-action.scss#L163) used from [our `:host(#{$prefix}-table-toolbar-search[expanded]) .bx--search` selector](https://github.com/carbon-design-system/carbon-web-components/blob/v1.13.0/src/components/data-table/_table-action.scss#L86)
