### ISSUE TITLE
[Lit]: upgrade to Lit 2.x

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-web-components#657]
### The problem

Blocked by https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9767

Carbon Web Components is currently running on v1.x of `lit-element` / `lit-html`. This is one of the fundamental libraries used for rendering web components within this repository.

### The solution

Investigate the level of effort for upgrading `carbon-web-components` to Lit 2.x. 

### Additional information

- Investigation should consider users that are currently on lit-html/lit-element, and if there is any messaging necessary to have users upgrade to lit 2. 
- `Carbon for IBM.com` web components uses `carbon-web-components` fundamentally, and should understand what the impact would be with this upgrade as well. (https://www.github.com/carbon-design-system/carbon-for-ibm-dotcom).
- Upgrade documentation: https://lit.dev/docs/releases/upgrade/

**Comment by RobertaJHahn** [comment]
To be added to the June 28 engineering issues refinement meeting agenda.

**Comment by gmosx** [comment]
Any decisions regarding this?

**Comment by RobertaJHahn** [comment]
@gmosx The investigation work has been scheduled in our next sprint, 21-17.  The dates are:  Aug 16 - 27.

**Comment by gmosx** [comment]
Thank you. It makes sense that the new version of Carbon uses the new version of lit. 🙏

**Comment by jeffchew** [comment]
Going through the upgrade steps, the updates are fairly straight forward, except for the custom `spread` directive: https://github.com/carbon-design-system/carbon-web-components/blob/master/src/globals/directives/spread.ts. 

According to documentation, the directive will need to be updated to 2.0 spec:

https://lit.dev/docs/releases/upgrade/#example-directive-migration

**Comment by abdonrd** [comment]
Regarding the spread directive, please check this: https://github.com/lit/lit/pull/1960

**Comment by jeffchew** [comment]
Thank you @abdonrd ! We will certainly keep an eye on that and ideally we can just use that when we upgrade to lit 2.0. 

For reference, a working branch of the upgrade (not PR ready yet):

https://github.com/jeffchew/carbon-web-components/commit/40ddff2b9480a07f4bb7f8333339e8323ec34c9a

The spread directive is probably one of the main things we are waiting on before we can hopefully move this forward.

**Comment by abdonrd** [comment]
I just see your branch.

Remember that you need to use the path with extensions:
```typescript
import { property, customElement } from 'lit/decorators.js';
```

```typescript
import { repeat } from 'lit-html/directives/repeat.js';
```

And there is already a new Lit RC: `lit@2.0.0-rc.3`

**Comment by jeffchew** [comment]
Thanks! I'll make those updates!

**Comment by tpluscode** [comment]
Looks like this is not happening this year?

FWIW, I can happily mix both major versions of lit and it keeps carbon happy

```json
{
  "dependencies": {
    "lit": "^2.0.2",
    "lit-element": "^2.5.1",
    "lit-html": "^1.4.1"
  }
}
```

The only problem I have encountered so far is that icons cannot be directly rendered inside lit@2 template

**Comment by abdonrd** [comment]
Reference to more projects migrated/migrating to Lit v2:

- https://github.com/adobe/spectrum-web-components/pull/1401
- https://github.com/patternfly/patternfly-elements/pull/1804

**Comment by jeffchew** [comment]
> Reference to more projects migrated/migrating to Lit v2:
> 
> * [feat: use "lit" instead of "lit-html" and "lit-element" adobe/spectrum-web-components#1401](https://github.com/adobe/spectrum-web-components/pull/1401)
> * [Update Lit to v2 ing-bank/lion#1489](https://github.com/ing-bank/lion/pull/1489)
> * [⚡ PatternFly Elements 2.0: Lit, TypeScript, pfe-tools, and more patternfly/patternfly-elements#1804](https://github.com/patternfly/patternfly-elements/pull/1804)

Thank you for the references!

I think we're still blocked on the spread directive. I saw some chatter about folks might try to roll their own instead, though we will have to evaluate if we can do the same.

**Comment by Westbrook** [comment]
I’m supposed to commit the one we use to OpenWC for publication as the main library will NOT be shipping one. I’ll try to get it together tomorrow to see if we can get enough voices involved to ship it soon!

**Comment by Westbrook** [comment]
https://github.com/open-wc/open-wc/pull/2398

**Comment by abdonrd** [comment]
Cool! Thanks @Westbrook!

@jeffchew there you have it! 🎉

**Comment by kennylam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-web-components/657?planning-poker) with ZenHub @ariellalgilmore @emyarod @IgnacioBecerra @jeffchew
