### ISSUE TITLE
<bx-radio-button> not checking on render if the radio-button is already checked.

### ISSUE THREAD

**Issue by rkgriff** [carbon-design-system/carbon-web-components#669]
[index_html.zip](https://github.com/carbon-design-system/carbon-web-components/files/6825249/index_html.zip)

## Detailed description

> Describe in detail the issue you're having.

Trying to submit a **form** with a **< bx-radio-button >** that is already checked when the page loads (i.e. - **not** checked by the user in the browser).  When the form is submitted the 'pre-checked' radio button value is **not** actually passed (i.e. - **not** added to the **Form Data**).  If I click on the already checked radio button, it works correctly.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

This is an issue. 

> Is this issue related to a specific component?

Yes, **< bx-radio-button >**

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Need to have the 'already checked' radio button value passed (i.e. - added to the **Form Data**) when the form is submitted.

> What browser are you working in?

Firefox and Chrome.

> What version of Carbon Web Components are you using?

1.13.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

**Fix Central** web application.  Function is required as part of Carbon migration from v18.  Target before year end.

## Steps to reproduce the issue

1. Load the '**index.html**' file from the attached '**index_html.zip**' file in a browser 
   (need to include a '/dist/bundle.js' file that includes **radio-button**, **radio-button-group** and **form-item**).
2. The 1st radio button should already be checked (**don't click it**).
3. Click the **submit** button.
4. Check the **Form Data** in the request to see the radio button / value is **not** there.

**Comment by rkgriff** [comment]
Confirmed the above issue while working with Ari Gilmore (Ariellalgilmore@ibm.com).  Need this resolved in order to migrate existing Fix Central application function from v18 to Carbon.  Thanks.

**Comment by asudoh** [comment]
Weighing in; Wondering if @ariellalgilmore @jeffchew and the team wants to encourage adopter to set `value` attribute `<bx-radio-button-group>` up-front, so the [`formdata` event handler](https://github.com/carbon-design-system/carbon-web-components/blob/v1.13.0/src/components/radio-button/radio-button-group.ts#L55-L61) can grab the value.

**Comment by rkgriff** [comment]
@asudoh  @ariellalgilmore @jeffchew  I'll give this a try as a workaround.  However, shouldn't the solution be to fix what Ariella suggested as the root cause (i.e. - "not checking on render if the radio-button is already checked.")?

**Comment by asudoh** [comment]
`value` property of `<bx-radio-button-group>` (instead of `checked` in `<bx-radio-button>` in above test case) is the source of truth for its form integration, and thus setting `value` up-front is the way to go.

**Comment by rkgriff** [comment]
@asudoh Thanks for the additional information.  I'll look at making this update and see if it resolves the issue.  If so, I'll delete this bug.  Thanks.

**Comment by jeffchew** [comment]
@rkgriff did the above resolve your issue?

@asudoh thank you for jumping in! The team misses you!

**Comment by rkgriff** [comment]
@jeffchew @asudoh  Hi, I was able to get the above scenario to work by pre-setting the` value` property of `<bx-radio-button-group>` when the page loads.  However, one scenario we also have in the application is to `check` a given `<bx-radio-button>` that corresponds to a given `<bx-input>` field, as soon as the user clicks into the `<bx-input>` field.  I had to modify our current JavaScript to not only `check` the appropriate `<bx-radio-button>`, but to also retrieve that buttons value and then update the `value` property of `<bx-radio-button-group>` with the same value, before submitting the form.  I would still prefer for the JavaScript to only have to `check` the appropriate `<bx-radio-button>`, and not have to worry about also setting the `value` property of `<bx-radio-button-group>` with it's value.  This is how the application currently works with HTML radio buttons / input fields.  If that can't be done, then I'll need to add my update in various places within the application.  Thoughts?  Thanks.

**Comment by asudoh** [comment]
Just in case it's worth noting, `value` of `<bx-radio-button-group>` is the only thing that needs to be set, and the corresponding radio button will be checked automatically.

**Comment by rkgriff** [comment]
@jeffchew  @asudoh  Sorry, I've been on vacation the last few days.  I understand that when the page loads, setting the `value` of the `<bx-radio-button-group>` is the only thing that needs to be set, and the corresponding radio button will be checked automatically.  However, one of our scenarios is to check a specific radio button via JavaScript when a particular `<bx-input>` field is clicked (i.e. - via its `onclick` event).  So, visually the user sees the specific radio button has been selected.  However, unless I now set the `value` of the `<bx-radio-button-group>` with that radio buttons value in the same JavaScript, it's never updated when the `<form>` is submitted.  I guess my overall question is why selecting a radio button via JavaScript doesn't cause the `value` of the `<bx-radio-button-group>` to be updated when the form is submitted.  Whereas, manually selecting the same radio button does.  This scenario currently works fine using HTML input fields / radio buttons, where the `onclick` JavaScript of an input field simply checks a given radio button.  It's value is used when the form is submitted.

**Comment by asudoh** [comment]
> selecting a radio button via JavaScript

@jeffchew Would you and the team want to sync up with the adopter team to demonstrate how it can be done? It can be done by setting `value` of `<bx-radio-button-group>`, changing `<bx-radio-button>` is _not_ needed. Thanks!

**Comment by ariellalgilmore** [comment]
Hi @asudoh and @rkgriff ! Thanks so much @asudoh for jumping in!! 

@rkgriff to follow up what @asudoh was explaining. 

If you take a look at how the storybook example is setup you have this: https://github.com/carbon-design-system/carbon-web-components/blob/f50c4515ea04f56865005cbb67e04d0497078434/src/components/radio-button/radio-button-story.ts#L34-L45

in the storybook example there is a value knob: https://web-components.carbondesignsystem.com/?path=/story/components-radio-button--default.

if you change that value knob to one of the values set in the each of the `radio-button`'s. Then you can see the proper update. For example if I change the knob value which is the `<bx-radio-button-group` `value` then it will select the corresponding `radio-button`

<img width="1220" alt="Screen Shot 2021-07-26 at 3 09 14 PM" src="https://user-images.githubusercontent.com/20210594/127065770-7e99ef98-ab1d-4dca-8828-e60a2fa48677.png">

**Comment by rkgriff** [comment]
@ariellalgilmore  Thanks for the detailed example, etc.  I modified my application to just update the `value` of the `<bx-radio-button-group>`, and removed anything I was doing to check an individual `<bx-radio-button>`.  It's working as you and @asudoh  described. Thank you both.

@jeffchew  This issue can be closed as 'not valid'.  Thanks.

**Comment by rkgriff** [comment]
@jeffchew  I guess I can close it.  Issue is not valid.  Closing.  Thanks.
