### ISSUE TITLE
bx-pages-select-changed event not being fired when arrow navigation in bx-pagination

### ISSUE THREAD

**Issue by patrickklick** [carbon-design-system/carbon-web-components#671]
## Detailed description

> When trying to handle the event when a page has changed, the event `bx-pages-select-changed` is not being sent out when the arrows are clicked within the `bx-pagination` component.

> Is this issue related to a specific component?
bx-pagination and bx-pages-select

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The event `bx-pages-select-changed` should be fired indicating that the page has changed when clicking on the arrows. The event only fires when a page size is chosen. Since the `bx-pages-select` component changes when arrows clicked, it should be the one to fire the event indicating that the page has changed.

> What browser are you working in?
Chrome

> What version of Carbon Web Components are you using?
1.13.0

## Steps to reproduce the issue

1. Once pagination has been loaded, click on the left or right arrow to navigate pages
2. Clicking on the arrow doesn't trigger the event
3. Changing the page through the dropdown does work however

## Additional information

```
<bx-pagination
    page-size="10"
    total="100"
    @bx-pages-select-changed=${({ detail }) => {
        console.log(`Page changed to ${detail.value}`);
    }}
>
    <bx-pages-select total="10" value="0"></bx-pages-select>
</bx-pagination>
```

**Comment by asudoh** [comment]
Weighing in; If you go to https://web-components.carbondesignsystem.com/?path=/story/components-pagination--default, open Actions tab at the bottom or at the right, and try arrow navigation in the component, you'll see `bx-navigation-changed-current` events logged. OTOH `bx-pages-select-changed` event is solely of the select box (not arrow).

**Comment by jeffchew** [comment]
@patrickklick confirmed that the actions are getting fired, can you see if this works for you?

![image](https://user-images.githubusercontent.com/1641214/126326604-2de29cfe-3db6-430c-b860-76465b83ddb4.png)

@asudoh thank you for jumping in!

**Comment by patrickklick** [comment]
Thanks @asudoh and @jeffchew for replying. We did discover the `bx-pagination-changed-current` event after playing with the component a bit more. The only thing that was beneficial with the `bx-pages-select-changed` event was that it told us directly which page we were going to. 

As a potential improvement, if the event `bx-pages-select-changed` was fired whenever the pages selector changed, it would be helpful to capture those events. Even if its not changed directly, it would still be helpful to have that event fired. 

Thanks for your help!

**Comment by asudoh** [comment]
Just in case it's worth noting, `bx-pagination-changed-current` is the only event that needs to be listened to - It's fired when the select box is changed as well as when arrow button is clicked on.

**Comment by patrickklick** [comment]
That is true. Thanks @asudoh.

**Comment by rccc** [comment]
> bx-navigation-changed-current

Hello, thi event is not referenced in the documentation page.

Eric
