### ISSUE TITLE
Bx-combo-box wrong behavior on filtering.

### ISSUE THREAD

**Issue by SoloveyDm** [carbon-design-system/carbon-web-components#692]
## Detailed description

https://codesandbox.io/s/github/carbon-design-system/carbon-web-components/tree/master/examples/codesandbox/cdn

1. Scroll the page so that the bx-combo-box is at the bottom of the page (see screenshot 1).
2. Enter any character in the filtration area.
3. This will cause the whole page to scroll up (see screenshot 2).

![screenshot_1](https://user-images.githubusercontent.com/89772242/131315824-75c44a44-ab7e-4e24-97ed-c4c6d2cbbb7a.jpg)
![screenshot_2](https://user-images.githubusercontent.com/89772242/131315827-42fd91c7-d366-465b-a119-095a828fd0f3.jpg)

**Comment by RobertaJHahn** [comment]
dup of #776.  Closing
