### ISSUE TITLE
Extending Carbon Web Components with Custom Styles

### ISSUE THREAD

**Issue by patrickklick** [carbon-design-system/carbon-web-components#700]
## Summary
We have started to adopt using Carbon Web Components in our repository. We decided that we wanted to add some minor UI tweaks to some of the components and also extend the component to adjust some of the colors (Using your suggested method [here](https://web-components.carbondesignsystem.com/?path=/docs/introduction-custom-styles--page#creating-derived-components-with-different-style)).

## Relevant information
We are using Carbon Web Components NPM package version `1.14.0` and developing our own NPM package to be able to import into our primary project. 

## Detailed description
When integrating with this method, we decided to create the new components to follow the same naming convention you have (we are using `gcr` instead of `bx` for components). Because of this rename, we discovered that some of the component styles (such as for `bx-btn`) use the element name within the `:host(` css selector. This causes some weird styling issues as the proper styles aren't applied to some sub components. As you can see in the screenshot below, the icon inside of the button component doesn't line up properly. That is because the styles for the icon placement are using `:host(bx-btn) ...` and that no longer is applicable in the element.

Is there a path forward you recommend in order for us to proceed with the renaming of the elements? We would like to keep the ability to extend the element to add our own styles (mostly around colors and small UI tweaks). We also want to avoid overriding those styles manually as it will complicate our integration and cause more dev time.

Screenshot:
**Using gcr-button (will be renamed to gcr-btn)**
![gcr-button-screenshot](https://user-images.githubusercontent.com/9828866/133485573-ebcdb8a9-b7dc-42a6-b2f4-a99404a5e545.png)

**Using bx-btn (updated in inspector for screenshot purposes)**
![bx-btn-screenshot](https://user-images.githubusercontent.com/9828866/133487031-d4f70907-dd94-42d2-aa40-35a09459e025.png)

Code Snippet:
```
import { css } from 'lit';
import BXButton from 'carbon-web-components/es/components/button/button';
import { REGISTRY_NAMESPACE } from '../../shared/js/constants';

export const ELEMENT_NAME = `${REGISTRY_NAMESPACE}-button`;
export default class GCRButton extends BXButton {
	static styles = [
		BXButton.styles,
		css`
            :host {
                --cds-button-primary: var(--gcr-primary);
                --cds-button-tertiary: var(--gcr-primary);
                --cds-button-primary-hover: var(--gcr-primary);
                --cds-button-tertiary-hover: var(--gcr-primary);
                --rounding: 2px;
                font-family: var(--gcr-font-family);
            }

            .bx--btn {
                border-radius: var(--rounding);
            }

            .bx--btn--primary:focus {
                background: var(--cds-focus,#0f62fe);
                /* box-shadow: inset 0 0 0 1px var(--cds-focus,#0f62fe),inset 0 0 0 2px var(--cds-ui-background,#fff); */
                box-shadow: unset;
            }

            .bx--btn--tertiary:focus, .bx--btn--tertiary:hover {
                background-color: rgba(0,0,0,0.05);
                color: var(--cds-interactive-03);
            }
	    `,
	];
}

if (!customElements.get(ELEMENT_NAME)) {
	customElements.define(ELEMENT_NAME, GCRButton);
}

**Comment by RobertaJHahn** [comment]
Jeff will include in the engineering huddle to determine the amount of effort to implement.

**Comment by patrickklick** [comment]
hey team! So I have seen some activity on this for the last couple of weeks. Its by no means urgent, but it makes it hard to proceed with our slightly customized versions of the components. We have worked around this for the time being.

Any ideas on when this will be available? Noticed that it went to `Low priority` and was removed as a `bug`.

**Comment by annawen1** [comment]
Hi @patrickklick apologies for such a late response! One thing I would like to ask, is forking the repository not an option?

**Comment by patrickklick** [comment]
Hi @annawen1 thanks for getting back to me. Technically, forking is an option for us but I would rather avoid it as it causes some other implications for us down the line. We have a workaround that seems to be working well. 

Part of the reason why I brought this up was to see if its possible, especially since you reference this type of style extending in the storybook documentation.

**Comment by annawen1** [comment]
@patrickklick gotcha, I'm investigating why it's not inheriting the styles. 

We're actually using the `carbon-web-components` in our `carbon-for-ibm-dotcom` web-components and overriding styles there as well.

I think that might be helpful to see the way we have it set up, our `dds-leaving-ibm-modal` in particular is extending `bx-modal`: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/leaving-ibm/leaving-ibm-modal.ts

and the styles are inherited and adjusted here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/leaving-ibm/leaving-ibm.scss

**Comment by patrickklick** [comment]
hey @annawen1,

Thanks for sending over the example. I see what you are doing now. I think the biggest difference is that I am not re-compiling the scss with the new variables. I will try this out on my side and see how things go as it might solve the issue we are having.

If the above does work, I would suggest an update to the documentation to include such information. 

Thanks again for looking into this for me!

**Comment by annawen1** [comment]
Closing this ticket as we have a working example in place, please feel free to re-open the ticket if there are additional issues/comments!
