### ISSUE TITLE
<MultiSelect.Filterable component select all, all items not selecting, although state updating in react.

### ISSUE THREAD

**Issue by hrshtpnt** [carbon-design-system/carbon-web-components#710]
![image](https://user-images.githubusercontent.com/22808323/136504128-f181a100-ab55-4dc7-ace3-55aed43ee702.png)

URGENT HELP NEEDED

I added select all option within the list, but the component does not re-render even when the state is changing and updating. Is there a way to re-render the component.

I tried to use a key prop key={Math.random()} with this my logic seems to work but the dropdown collapses/re-renders on each item select.

**Comment by emyarod** [comment]
it looks like you are using the Carbon React component which does not support fully uncontrolled use cases, so the menu closing is a direct result of rerendering the component (because the key prop is needed)

**Comment by emyarod** [comment]
@hrshtpnt according to the code sandbox you provided you're using `carbon-components-react` and not `carbon-web-components`, is that right? if so, then the issue would be just as we discussed (currently no workaround for rerendering the component with a `key` in your use case).  you would need to keep an eye on the other issue you created (carbon-design-system/carbon#9819) for further info on the React implementation

**Comment by hrshtpnt** [comment]
Yes I am using `carbon-components-react`. @emyarod  are you implying that if I use the [carbon-web-components](https://web-components.carbondesignsystem.com/?path=/docs/components-multi-select--default) I will be able to achieve my goal?
I am only looking for a way to update the components when the prop`selectedItem` change. This is expected behaviour in react components right? Does carbon internally controls when to update the components by using something like `React.memo`?
