### ISSUE TITLE
Update Node to LTS version

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-web-components#733]
### The problem

We are not using the Node LTS version

### The solution

Update Node to LTS version

### Application/website

-

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by jeffchew** [comment]
Doing a quick test run, it looks like `node-sass` is at least one of the culprits:

<img width="1127" alt="Screen Shot 2021-11-02 at 10 38 56 AM" src="https://user-images.githubusercontent.com/1641214/139869260-06545d11-f76f-4324-bfa4-34fb054ae7f1.png">
