### ISSUE TITLE
[Combo Box] Page scroll when typing in combo box

### ISSUE THREAD

**Issue by frodesigns** [carbon-design-system/carbon-web-components#776]
### Description

When typing in a combo box, the page scrolls down and is jarring to the user.

 

### Component(s) impacted

This is reproducible in Storybook: https://web-components.carbondesignsystem.com/?path=/story/components-combo-box--default

Here is a video of the issue:
https://user-images.githubusercontent.com/6588808/141011615-699d0107-2b95-47d8-9c1c-80a79796956e.mp4

### Browser

Chrome

### Carbon Web Components version

Latest

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

Kyndryl Catalyst

### CodeSandbox example

Storybook

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by emyarod** [comment]
related https://github.com/carbon-design-system/carbon-web-components/issues/722

**Comment by frodesigns** [comment]
Hello. I don't think this issue is actually related to storybook in any way.  Catalyst leadership is asking for an escalation to fix this since it is impacting the main UX of the application.
