### ISSUE TITLE
Slider doesn't work on touch devices

### ISSUE THREAD

**Issue by korgan00** [carbon-design-system/carbon-web-components#830]
### Description

Slider should work dragging in touch devices and it doesn't work

### Component(s) impacted

Slider (bx-slider)

### Browser

Chrome

### Carbon Web Components version

1.18.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

learn.qiskit.org

### CodeSandbox example

https://web-components.carbondesignsystem.com/react/index.html?path=/story/components-slider--default

### Steps to reproduce the issue (if applicable)

1. Using a touch device (also fail with chrome emulator).
2. Try to drag the thumb

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by korgan00** [comment]
I tried replacing mouse events with the generic [pointer-events](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event). It starts to react but for some reason, after some time (less than a second) it stops working.

**Comment by andy-blum** [comment]
@RobertaJHahn @jeffchew @proeung 

I'm working on this during the holiday lull.
