### ISSUE TITLE
[Storybook]: Webcomponents File Upload Wrong Events Documentation 

### ISSUE THREAD

**Issue by thoeby** [carbon-design-system/carbon-web-components#918]
### Description

Issue on the storrybook documentation for webcomponents. Seems like the table cut of the event description and the rest of it is on the next column. 

### Component(s) impacted

File uploader (Storybook)

### Carbon Web Components version

1.18.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

https://web-components.carbondesignsystem.com

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/docs/components-file-uploader--default

### Steps to reproduce the issue (if applicable)

`<bx-file-uploader-item>`-Events Documentation wrong/incorrect

Is state: `bx-file`
Correct: `bx-file-uploader-item-beingdeleted`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by thoeby** [comment]
@jeffchew found a couple of other errors documentation on storybook-doc. Should I post them as issues here on github or is there a better way?

**Comment by jeffchew** [comment]
> @jeffchew found a couple of other errors documentation on storybook-doc. Should I post them as issues here on github or is there a better way?

Yes, please create new issues, thanks!
