### ISSUE TITLE
Bundles with multiple components contain duplicated CSS

### ISSUE THREAD

**Issue by grommett** [carbon-design-system/carbon-web-components#952]
### The problem

When bundling each component imports its own css as a result a lot of css is duplicated. For example, reset CSS.

### The solution

Some form of de-duplication in the CSS where the build only adds what's needed.

### Application/website

IBM Internal (Operations Dashboard)

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### What time frame would this ideally be needed by (if applicable)

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by kennylam** [comment]
@grommett Can you provide more details on package(s) and version being used, and/or an example that can be viewed online?
Also fyi, this year with the migration to Carbon V11 and sass modules, duplicated styles from imports will be a thing of the past (fingers crossed).

**Comment by grommett** [comment]
Hi @kennylam,

Good news about V11 🎉 and thanks for investigating.

Version details:
- `carbon-components: 10.54.0`
- `carbon-web-components: 1.21.0`

Here is an extremely paired down repo to reproduce with instructions etc
https://github.com/grommett/carbon-duplicate-css-repro
