### ISSUE TITLE
New Version of Carbon: No mention of it anywhere here. Whats the status?

### ISSUE THREAD

**Issue by prodkt** [carbon-design-system/carbon-web-components#997]
### Summary

Looked for an hour not to have to bother y'all. But I'm curious what the plan here is for Carbon 11? I'm very interested in giving one of the Carbon outputs a try and potentially attempting to contribute. I'm just evaluating through each. Web Components do peak my brain for their framework-free approach. But I'd like to start with something up-to-date and/or not going to change too quickly on me.

### Name and organization

Bryan Funk | Prodkt

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by jeffchew** [comment]
Hi @prodkt !

The v11 upgrade of Carbon Web Components is actively in flight now! We will announce when it will come out, but we are anticipating the middle of this year!

Check out www.carbondesignsystem.com for updated news!

cc: @ljcarot @kennylam @oliviaflory
